Feature
didymus707/Apple-Site-clone pull request #1
Opened 2019-11-12 23:53 UTC by didymus707

Project completed

2019-11-13 00:10 UTC, Redvanisation requested changes
# Changes required  🛑

### Hello @didymus707   🌟

**Good work on this project, but we need to fix the issues below before moving on ⬇️** 

1. Please center the 4 bottom elements to the center of the page.

2. Set up Stickler to lint the CSS on your project, find out more on how to do that in [here](https://github.com/microverseinc/linters-config/tree/master/css)

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2019-11-13 00:10 UTC, Redvanisation commented on css/style.css
> +  /* height: 10vh; */
Please delete commented code

2019-11-13 00:10 UTC, Redvanisation commented on css/style.css
> +  /* height: 29vh; */
Commented code should be deleted

2019-11-13 00:31 UTC, didymus707 commented on css/style.css
> +  /* height: 29vh; */
changes made

2019-11-13 17:15 UTC, suretrust requested changes
Hi @didymus707,

### Great job thus far, your `readME` is lit! Please see my comments on your code.

Also, let's set up the linter properly, it should display as shown below when properly setup.
![linter2](https://user-images.githubusercontent.com/31304943/68783686-a936cf00-063b-11ea-8d27-532500ba2979.png)

**Kindly submit for another code review once these issues have been fixed.** _Happy coding!_ :tada:

2019-11-13 17:15 UTC, suretrust commented on .editorconfig
> +insert_final_newline = false
This should be added to `gitignore`, let's delete the file from the repo.

2019-11-13 17:15 UTC, suretrust commented on css/style.css
> +}
The total width of these images should be the same as the width of the background image above it.

![width](https://user-images.githubusercontent.com/31304943/68782882-5f99b480-063a-11ea-8809-49cab4d71e56.png)

2019-11-13 17:15 UTC, suretrust commented on index.html
> +  </div>
You can extend the `<main>` up to here since everything above footer is still main content.

2019-11-13 22:35 UTC, didymus707 commented on index.html
> +  </div>
All changes made

2019-11-13 22:35 UTC, didymus707 commented on css/style.css
> +}
Changes made

2019-11-13 22:36 UTC, didymus707 commented on .editorconfig
> +insert_final_newline = false
Changes made

2019-11-14 01:00 UTC, Redvanisation approved these changes
# Project approved ✔️ 

### Hello @didymus707  🌟 

### _Nice work on this project, it seems that you have met the requirements so I am approving your project. 👍_ 

### You may merge to master and submit a project completion form. 🚀 

### Good luck! 🍀

2019-11-14 12:55 UTC, merged